ln -s $HOME/local/dotfiles/.zlogin $HOME/.zlogin
ln -s $HOME/local/dotfiles/.zshenv $HOME/.zshenv
ln -s $HOME/local/dotfiles/.zshrc $HOME/.zshrc
ln -s $HOME/local/dotfiles/.zsh.d $HOME/.zsh.d
ln -s $HOME/local/dotfiles/.vim $HOME/.vim
ln -s $HOME/local/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/local/dotfiles/.emacs.d $HOME/.emacs.d
ln -s $HOME/local/dotfiles/.screenrc $HOME/.screenrc
ln -s $HOME/local/dotfiles/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/local/dotfiles/.tmux.conf.linux $HOME/.tmux.conf.local
ln -s $HOME/local/dotfiles/.gitconfig $HOME/.gitconfig
ln -s $HOME/local/dotfiles/.gitignore.global $HOME/.gitignore.global
